# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
production:
  adapter:  mysql2
  database: pbtourist
  host:     localhost
  username: root
  password: sam8888
  encoding: utf8

development:
  adapter:  mysql2
  database: pbtourist_development
  host:     localhost
  username: root
  password: sam8888
  encoding: utf8

test:
  adapter:  mysql2
  database: pbtourist_test
  host:     localhost
  username: root
  password: sam8888
  encoding: utf8
